# Overrides for the IDV Docker-Compose file

version: '3.4'
services:
  validation-module:
    image: idvtoolkit/validationmodule:${TAG:-latest}
#    build: ValidationModule/
    volumes:
      - ./ValidationModule:/opt/app/plugins
#     - ./ValidationModule/config:/opt/app/config/config
