# Compose file for the IDV
#
# This compose file defines all services used by the IDV.
#
# It supports docker compose (docker-compose up -d)
# and docker swarm (docker stack deploy --compose-file docker-compose.yml idv)

version: '3.4'
services:
  mongodb:
    image: mongo:4.4.0-rc10
    container_name: mongodb
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
    ports:
      - 5672:5672
      - 15672:15672

  attestation-module:
    image: ${REGISTRY}/idvtoolkit/attestationmodule:${TAG:-latest}
    container_name: attestation-module
    environment:
      - NODE_CONFIG_DIR
      - NODE_ENV
      - DB_SERVICE
      - RABBITMQ_SERVICE
      - DEBUG
    ports:
      - 8080:8080
    volumes:
      - ./config/attestationmodule:/opt/app/config/plugins
    depends_on:
      - mongodb

  credential-module:
    image: ${REGISTRY}/idvtoolkit/credentialmodule:${TAG:-latest}
    container_name: credential-module
    environment:
      - NODE_CONFIG_DIR
      - NODE_ENV
      - DB_SERVICE
      - RABBITMQ_SERVICE
      - DEBUG
    ports:
      - 4040:8080
      - 9228:9229
    volumes:
      - ./config/credentialmodule:/opt/app/config/plugins
    depends_on:
      - mongodb
      - sign-module
    healthcheck:
      test: ["CMD", "wget", "http://localhost:8080/health?includeExternal=true", '-O', '-']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  sign-module:
    image: ${REGISTRY}/idvtoolkit/signmodule:${TAG:-latest}
    container_name: sign-module
    environment:
      - NODE_CONFIG_DIR
      - NODE_ENV
      - DEBUG
    ports:
      - 5050:8080
    volumes:
      - ./config/signmodule:/opt/app/config/plugins

  validation-module:
    image: ${REGISTRY}/idvtoolkit/validationmodule:${TAG:-latest}
    container_name: validation-module
    environment:
      - NODE_CONFIG_DIR
      - NODE_ENV
      - DB_SERVICE
      - RABBITMQ_SERVICE
      - DEBUG
    ports:
      - 6060:8080
      - 9229:9229
    volumes:
      - ./config/validationmodule:/opt/app/config/plugins
    depends_on:
      - mongodb
      - rabbitmq
      - sign-module
    healthcheck:
      test: ["CMD", "wget", "http://localhost:8080/health?includeExternal=true", '-O', '-']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  data-retention-module:
    image: $REGISTRY/idvtoolkit/dataretentionmodule:${TAG:-latest}
    container_name: data-retention-module
    environment:
      - NODE_CONFIG_DIR
      - NODE_ENV
      - DEBUG
      - RABBITMQ_SERVICE
    ports:
      - 7070:8080
    volumes:
      - ./config/validatorportal:/opt/app/config/plugins:ro
    depends_on:
      - rabbitmq

  validator-portal:
    image: ${REGISTRY}/idvtoolkit/validatorportal:${TAG:-latest}
    container_name: validator-portal
    environment:
      - NODE_CONFIG_DIR
      - NODE_ENV
      # create-react-app reserves NODE_ENV for the value 'production'
      - STAGE
      - DB_SERVICE
      - RABBITMQ_SERVICE
      - DEBUG
    ports:
      - 3000:3000
    volumes:
      - $HOME/.aws:/root/.aws:ro
      - ./config/validatorportal:/opt/app/config/plugins:ro
    depends_on:
      - sign-module

  scheduler:
    image: ${REGISTRY}/idvtoolkit/scheduler:${TAG:-latest}
    container_name: scheduler
    environment:
      - ATTESTATION_MODULE_HOST
      - ATTESTATION_MODULE_PORT
      - CREDENTIAL_MODULE_HOST
      - CREDENTIAL_MODULE_PORT
      - VALIDATION_MODULE_HOST
      - VALIDATION_MODULE_PORT

  mobile-interface:
    image: ${REGISTRY}/idvtoolkit/mobileinterface:${TAG:-latest}
    ports:
      - 4000:8080
    volumes:
      - ./config/mobileinterface:/opt/app/config/plugins:ro
    environment:
      - MOBILE_INTERFACE_HTTP_PORT
      - MOBILE_INTERFACE_ATTESTATION_PATH
      - MOBILE_INTERFACE_ATTESTATION_ENDPOINT
      - MOBILE_INTERFACE_CREDENTIAL_PATH
      - MOBILE_INTERFACE_CREDENTIAL_ENDPOINT
      - MOBILE_INTERFACE_VALIDATION_PATH
      - MOBILE_INTERFACE_VALIDATION_ENDPOINT
      - MOBILE_INTERFACE_DATARETENTION_PATH
      - MOBILE_INTERFACE_DATARETENTION_ENDPOINT
      - NODE_CONFIG_DIR
      - GATEWAY_CONFIG
      - NODE_ENV
      - LOG_LEVEL
      - DEBUG

  admin-interface:
    image: ${REGISTRY}/idvtoolkit/admininterface:${TAG:-latest}
    ports:
      - 4050:8080
    volumes:
      - ./config/admininterface:/opt/app/config/plugins:ro
    environment:
      - ADMIN_INTERFACE_HTTP_PORT
      - ADMIN_INTERFACE_ATTESTATION_PATH
      - ADMIN_INTERFACE_ATTESTATION_ENDPOINT
      - ADMIN_INTERFACE_CREDENTIAL_PATH
      - ADMIN_INTERFACE_CREDENTIAL_ENDPOINT
      - ADMIN_INTERFACE_VALIDATION_PATH
      - ADMIN_INTERFACE_VALIDATION_ENDPOINT
      - ADMIN_INTERFACE_DATARETENTION_PATH
      - ADMIN_INTERFACE_DATARETENTION_ENDPOINT
      - NODE_CONFIG_DIR
      - GATEWAY_CONFIG
      - NODE_ENV
      - LOG_LEVEL
      - DEBUG

  notification-interface:
    image: ${REGISTRY}/idvtoolkit/notificationinterface:${TAG:-latest}
    ports:
      - 4060:8080
    volumes:
      - ./config/notificationinterface:/opt/app/config/plugins:ro
    environment:
      - NODE_CONFIG_DIR
      - NODE_ENV
      - DEBUG

