# Overrides for the IDV Docker-Compose file

version: '3.4'
services:
  validation-module:
#    image: idvtoolkit/validationmodule:${TAG:-latest}
#    build: ValidationModule/
    environment:
      - NODE_CONFIG_DIR=/opt/app/config
    volumes:
      - ./ValidationModule:/opt/app/plugins
#     - ./ValidationModule/config:/opt/app/config/config
