# Overrides for the IDV Docker-Compose file

version: '3.4'
services:
  validation-module:
#    image: idvtoolkit/validationmodule:${TAG:-latest}
#    build: ValidationModule/
    environment:
      NODE_CONFIG: ${CONFIG_OVERRIDE}
    volumes:
      - ./ValidationModule:/opt/app/plugins
      - ./ValidationModule/src/config:/opt/app/src/config
