forceSslRedirect: true
sslRedirect: true

pods:
  image:
    # identity.com AWS ECR repository
    registry: 146055947386.dkr.ecr.us-east-1.amazonaws.com/
  imagePullPolicy: Always
  labels:
    requiresAwsCreds: false

services:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0

mongodb:
  fullnameOverride: mongodb
  internal: true
  auth:
    enabled: false
  persistence:
    storageClass: gp2

rabbitmq:
  fullnameOverride: rabbitmq
  internal: true
  auth:
    existingPasswordSecret: rabbitmq
    existingErlangSecret: rabbitmq
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
  persistence:
    enabled: false

storage:
  useExisting: true

attestationmodule:
  basePath: /attestation
  resources:
    limits:
      cpu: 1
      memory: 2G
    requests:
      cpu: 0.5
      memory: 1G

credentialmodule:
  basePath: /credential
  resources:
    limits:
      cpu: 1
      memory: 2G
    requests:
      cpu: 0.5
      memory: 1G

validationmodule:
  basePath: /validation
  resources:
    limits:
      cpu: 2
      memory: 4G
    requests:
      cpu: 1
      memory: 2G

dataretentionmodule:
  basePath: /dataretention
  resources:
    limits:
      cpu: 1
      memory: 2G
    requests:
      cpu: 0.5
      memory: 1G

newrelic:
  enabled: false

admininterface:
  basePath: /admin

mobileinterface:
  resources:
    limits:
      cpu: 2
      memory: 4G
    requests:
      cpu: 1
      memory: 2G

notificationinterface:
  basePath: /notifications
  resources:
    limits:
      cpu: 1
      memory: 2G
    requests:
      cpu: 0.5
      memory: 1G

validatorportal: {}

signmodule: {}

analytics:
  enabled: false

analyticsmodule:
  resources:
    # https://docs.aws.amazon.com/eks/latest/userguide/fargate-pod-configuration.html
    limits:
      cpu: 1
      memory: 2G
    requests:
      cpu: 0.5
      memory: 1G
