apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-no-path-rewrite
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: {{ quote .Values.sslRedirect }}
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/force-ssl-redirect: {{ quote .Values.forceSslRedirect }}
spec:
  tls:
    - hosts:
      - {{ .Values.host }}
      secretName: {{ .Values.host }}-tls
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      #MobileInterface
      - path: {{ .Values.attestationmodule.basePath }}
        backend:
          serviceName: mobile-interface
          servicePort: 80
      - path: {{ .Values.credentialmodule.basePath }}
        backend:
          serviceName: mobile-interface
          servicePort: 80
      - path: {{ .Values.validationmodule.basePath }}
        backend:
          serviceName: mobile-interface
          servicePort: 80
      - path: {{ .Values.dataretentionmodule.basePath }}
        backend:
          serviceName: mobile-interface
          servicePort: 80
