apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  tls:
    - hosts:
      - {{ .Values.host }}
      secretName: {{ .Values.host }}-tls
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      # Validator Portal
      - path: /validator
        backend:
          serviceName: {{ .Release.Name }}-validator-portal
          servicePort: 80
      # Notification Interface
      - path: {{.Values.notificationinterface.basePath}}
        backend:
          serviceName: {{ .Release.Name }}-notification-interface
          servicePort: 80
