apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  tls:
    - hosts:
      - {{ .Values.host }}
      secretName: {{ .Values.host }}-tls
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      # Validator Portal
      - path: /validator(/|$)(.*)
        backend:
          serviceName: validator-portal
          servicePort: 80
      # Notification Interface
      - path: {{.Values.notificationinterface.basePath}}(/|$)(.*)
        backend:
          serviceName: notification-interface
          servicePort: 80
