apiVersion: v1
kind: Service
metadata:
  name: admin-interface
spec:
  type: LoadBalancer
  selector:
    app: admin-interface
  ports:
  - port: 80
    targetPort: http
  loadBalancerSourceRanges:
    {{- range .Values.admininterface.sourceRanges }}
    - {{ . }}
    {{- end }}
