apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-interface
  labels:
    app: notification-interface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-interface
  template:
    metadata:
      labels:
        app: notification-interface
        requires-aws-creds: "{{ .Values.pods.labels.requiresAwsCreds }}"
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: notification-interface
          image: {{ .Values.pods.image.registry }}idvtoolkit/notificationinterface:{{ .Values.pods.image.tag }}
          imagePullPolicy: {{ .Values.pods.imagePullPolicy }}
          env:
            # The location of the application config - mapped by the config volume
            # and populated by the idvtoolkit/config
            - name: NODE_CONFIG_DIR
              value: /opt/app/config:/opt/app/config/plugins:/opt/app/config/plugins/secrets
            - name: NODE_ENV
              value: {{ .Values.pods.environment }}
            - name: NEW_RELIC_ENABLED
              value: "false" #  "{{ .Values.newrelic.enabled }}"  # hard-code false for non-critical components to save NR costs
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            # Exposes the config to the application
            - mountPath: /opt/app/config/plugins
              name: config
              readOnly: true
            - mountPath: /opt/app/config/plugins/secrets
              name: secrets
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: notification-interface-config
        - name: secrets
          secret:
            secretName: notification-interface-secret
