{{- if .Values.analytics.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: analytics-secret
type: Opaque
data:
{{ (.Files.Glob "config/admininterface/secret/*").AsConfig | indent 2 }}
{{- end}}
