apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  labels:
    app: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
        requires-aws-creds: "{{ .Values.pods.labels.requiresAwsCreds }}"
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: scheduler
          image: {{ .Values.pods.image.registry }}idvtoolkit/scheduler:{{ .Values.pods.image.tag }}
          imagePullPolicy: {{ .Values.pods.imagePullPolicy }}
          env:
            - name: ATTESTATION_MODULE_HOST
              value: attestation-module
            - name: ATTESTATION_MODULE_PORT
              value: "80"
            - name: CREDENTIAL_MODULE_HOST
              value: credential-module
            - name: CREDENTIAL_MODULE_PORT
              value: "80"
            - name: VALIDATION_MODULE_HOST
              value: validation-module
            - name: VALIDATION_MODULE_PORT
              value: "80"
