apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-credential-module
  {{- if .Values.services.annotations }}
  annotations:
    {{ toYaml .Values.services.annotations }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    app: credential-module
  ports:
  - port: 80
    targetPort: http