apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sign-module
  labels:
    app: sign-module
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sign-module
  template:
    metadata:
      labels:
        app: sign-module
        requires-aws-creds: "{{ .Values.pods.labels.requiresAwsCreds }}"
    spec:
      containers:
        - name: sign-module
          image: {{ .Values.pods.image.registry }}idvtoolkit/signmodule:{{ .Values.pods.image.tag }}
          imagePullPolicy: {{ .Values.pods.imagePullPolicy }}
          env:
            # The location of the application config - mapped by the config volume
            # and populated by the idvtoolkit/config
            - name: NODE_CONFIG_DIR
              value: /opt/app/config/config/signmodule
            {{- if .Values.signmodule.config }}
            - name: NODE_CONFIG
              value: {{ .Values.signmodule.config | quote }}
            {{- end}}
            # currently set to preprod only TODO move this to values.yaml
            - name: NODE_ENV
              value: {{ .Values.pods.environment }}
            - name: NEW_RELIC_ENABLED
              value: "{{ .Values.newrelic.enabled }}"
          ports:
            - name: http
              containerPort: 3030
          volumeMounts:
            # Exposes the config to the application
            - mountPath: /opt/app/config
              name: config
              readOnly: true
          readinessProbe:
            httpGet:
              path: /health?includeExternal=true
              port: http
            initialDelaySeconds: 3
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /health?includeExternal=true
              port: http
            initialDelaySeconds: 3
            periodSeconds: 30
      initContainers:
        # Loads secrets and sends the config to the application via the config volume
        - name: config
          image: {{ .Values.pods.image.registry }}idvtoolkit/config:{{ .Values.pods.image.tag }}
          imagePullPolicy: {{ .Values.pods.imagePullPolicy }}
          # PodPresets do not currently apply to InitContainers https://github.com/kubernetes/kubernetes/issues/55410
          {{ if .Values.pods.labels.requiresAwsCreds }}
          env:
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.aws_access_key_id }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.aws_secret_access_key }}
          {{ end }}
          volumeMounts:
            - mountPath: /resolvedConfig
              name: config
      volumes:
        - name: config
          # Uses tmpfs to avoid storing secrets on disk
          emptyDir: {"medium":"Memory"}
