apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-validator-portal
  labels:
    app: validator-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validator-portal
  template:
    metadata:
      labels:
        app: validator-portal
        requires-aws-creds: "{{ .Values.pods.labels.requiresAwsCreds }}"
    spec:
      containers:
        - name: validator-portal
          image: {{ .Values.pods.image.registry }}idvtoolkit/validatorportal:{{ .Values.pods.image.tag }}
          imagePullPolicy: {{ .Values.pods.imagePullPolicy }}
          env:
            - name: NODE_CONFIG_DIR
              value: /opt/app/config/config/validatorportal/backend
            {{- if .Values.validatorportal.config }}
            - name: NODE_CONFIG
              value: {{ .Values.validatorportal.config | quote }}
            {{- end}}
            - name: NODE_ENV
              value: {{ .Values.pods.environment }}
            - name: STAGE
              value: {{ .Values.pods.environment }}
            - name: VALIDATOR_PORTAL_ROUTE
              value: validator
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
            - mountPath: /opt/app/config
              name: config
              readOnly: true
      initContainers:
        - name: config
          image: {{ .Values.pods.image.registry }}idvtoolkit/config:{{ .Values.pods.image.tag }}
          imagePullPolicy: {{ .Values.pods.imagePullPolicy }}
          # PodPresets do not currently apply to InitContainers https://github.com/kubernetes/kubernetes/issues/55410
          {{ if .Values.pods.labels.requiresAwsCreds }}
          env:
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.aws_access_key_id }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.aws_secret_access_key }}
          {{ end }}
          volumeMounts:
            - mountPath: /resolvedConfig
              name: config
      volumes:
        - name: config
          emptyDir: {"medium":"Memory"}
