# This secret file is copied from the rabbitmq subchart, and ensures that a
# new secret is created for rabbitmq on install only. Subsequent updates
# use the existing one.
# For this to work, existingPasswordSecret and existingErlangSecret must be
# true in values.yaml (to prevent the subchart from generating its own secret).
{{ if or ( .Release.IsInstall ) (or (not .Values.rabbitmq.rabbitmq.existingErlangSecret) (not .Values.rabbitmq.rabbitmq.existingPasswordSecret)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rabbitmq.fullnameOverride }}
  labels:
    app: {{ .Values.rabbitmq.fullnameOverride }}
  annotations:
    # prevents helmm from deleting this when Release.IsInstall is false
    helm.sh/resource-policy: "keep"
type: Opaque
data:
  rabbitmq-password: {{ randAlphaNum 10 | b64enc | quote }}
  rabbitmq-erlang-cookie: {{ randAlphaNum 32 | b64enc | quote }}
{{ end }}
