{{- if ne .Values.storage.useExisting true }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: standard
provisioner: {{ .Values.storage.provisioner }}
{{- with .Values.storage.parameters }}
parameters:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
